spring.application.name=backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#The official Google endpoint that provides public keys used to verify
#the validity of Firebase Authentication generated JWTs.
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
stripe.secretKey=${STRIPE_SECRET_KEY:}

# Cloud function URL for sending appointment cancellation notifications.
bouh.cloud-function.cancellation-url=${CANCELLATION_FUNCTION_URL:https://us-central1-bouh-94761.cloudfunctions.net/sendCancellationNotification}

#Gemini API
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
