// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBEwffGfunMK6-MjBZRxfbIXdDm4S6rO0',
    appId: '1:1065699977643:ios:4df2406f518d74fbd34aee',
    messagingSenderId: '1065699977643',
    projectId: 'bouh-94761',
    storageBucket: 'bouh-94761.firebasestorage.app',
    iosBundleId: 'com.example.bouh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBEwffGfunMK6-MjBZRxfbIXdDm4S6rO0',
    appId: '1:1065699977643:ios:4df2406f518d74fbd34aee',
    messagingSenderId: '1065699977643',
    projectId: 'bouh-94761',
    storageBucket: 'bouh-94761.firebasestorage.app',
    iosBundleId: 'com.example.bouh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk_pom7o_1IylBhaLr_3C1_ueBZBBinV8',
    appId: '1:1065699977643:web:fb9de7b5f7c34b92d34aee',
    messagingSenderId: '1065699977643',
    projectId: 'bouh-94761',
    authDomain: 'bouh-94761.firebaseapp.com',
    storageBucket: 'bouh-94761.firebasestorage.app',
    measurementId: 'G-QNJQTTGFLJ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk_pom7o_1IylBhaLr_3C1_ueBZBBinV8',
    appId: '1:1065699977643:web:fb9de7b5f7c34b92d34aee',
    messagingSenderId: '1065699977643',
    projectId: 'bouh-94761',
    authDomain: 'bouh-94761.firebaseapp.com',
    storageBucket: 'bouh-94761.firebasestorage.app',
    measurementId: 'G-QNJQTTGFLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEV8QXtqTdnpFpx3-pzJ9ZzB_GH_ew3nQ',
    appId: '1:1065699977643:android:9f48df8fd3763b0ed34aee',
    messagingSenderId: '1065699977643',
    projectId: 'bouh-94761',
    storageBucket: 'bouh-94761.firebasestorage.app',
  );

}