class AppointmentDto {
  final String? appointmentId; // generated by backend
  final String caregiverId;
  final String doctorId;
  final String childId;
  final String date;
  final String timeSlotId;
  final String? meetingLink; // backend controlled
  final int amount;
  final String? status; // backend controlled
  final String paymentIntentId; //  important for refund

  AppointmentDto({
    this.appointmentId,
    required this.caregiverId,
    required this.doctorId,
    required this.childId,
    required this.date,
    required this.timeSlotId,
    this.meetingLink,
    required this.amount,
    this.status,
    required this.paymentIntentId,
  });

  /// Used when creating appointment
  Map<String, dynamic> toJson() => {
    "caregiverId": caregiverId,
    "doctorId": doctorId,
    "childId": childId,
    "date": date,
    "timeSlotId": timeSlotId,
    "amount": amount,
    "paymentIntentId": paymentIntentId,
  };

  /// Used when reading from backend
  factory AppointmentDto.fromJson(Map<String, dynamic> json) {
    return AppointmentDto(
      appointmentId: json["appointmentId"],
      caregiverId: json["caregiverId"],
      doctorId: json["doctorId"],
      childId: json["childId"],
      date: json["date"],
      timeSlotId: json["timeSlotId"],
      meetingLink: json["meetingLink"],
      amount: json["amount"],
      status: json["status"],
      paymentIntentId: json["paymentIntentId"] ?? "",
    );
  }
}
